In [1]:
# Selecciona Income y Período para descargar: 
IncomeFile = "Ingresos2020.csv"
Periodo = 'Anual' # 'Anual' si es Resultado del Año. 'Q1'..'Q4' si es Trimestral.

### Tranformación Automatizada Datos Holded:

In [2]:
import pandas as pd 
import numpy as np

In [3]:
# Importamos data:
    # IncomeFile = "Ingresos2022.csv"
    # Periodo = 'Anual'

Ingresos = pd.read_csv(f"/home/claude/holded/HoldedFiles/{IncomeFile}", header = None, sep = '\t')

In [4]:
# Renombramos nombres de columnas:
Ingresos = Ingresos.rename(columns={0 : 'Subcuenta', 1 : 'Valor'})

* 0. Cabecera y pie de página:

In [5]:
# Borramos filas totalmente vacías (relleno del export de Holded):
Ingresos = Ingresos.dropna(subset=['Subcuenta', 'Valor'], how='all')

In [6]:
Ingresos

                                            Subcuenta        Valor
0                                             Tet¡xto          NaN
1                                             Tet¡xto          NaN
2                           01/01/2020  -  31/12/2020          NaN
4                                                 NaN        Total
5             1. Importe neto de la cifra de negocios  3268788,014
..                                                ...          ...
74                         Impuestos sobre beneficios  -36661,8804
75                      63000000 - IMPUESTO CORRIENTE  -36661,8804
76                                                NaN            0
77                            Resultado del ejercicio  109985,6412
80  Informe creado automáticamente con Holded - 12...          NaN

[78 rows x 2 columns]

In [7]:
# Textos fijos de cabecera y pie que trae siempre el informe de Holded:
Textos_informe = pd.Series(['Tet¡xto', 'Informe creado automáticamente'])
print(Textos_informe)

0                           Tet¡xto
1    Informe creado automáticamente
dtype: str

In [8]:
# Borramos cabecera (título, rango de fechas) y pie de página:
Ingresos = Ingresos[~Ingresos['Subcuenta'].str.contains('|'.join(Textos_informe), na=False)]
Ingresos = Ingresos[~Ingresos['Subcuenta'].str.match(r'^\d{2}/\d{2}/\d{4}', na=False)]
Ingresos = Ingresos[Ingresos['Valor'] != 'Total']

In [9]:
Ingresos

                                  Subcuenta         Valor
5   1. Importe neto de la cifra de negocios   3268788,014
6              b) Prestaciones de servicios   3268788,014
7      70500000 - PRESTACIONES DE SERVICIOS   3268788,014
8                                       NaN             0
9                     4. Aprovisionamientos  -849222,7309
..                                      ...           ...
73           19. Impuestos sobre beneficios   -36661,8804
74               Impuestos sobre beneficios   -36661,8804
75            63000000 - IMPUESTO CORRIENTE   -36661,8804
76                                      NaN             0
77                  Resultado del ejercicio   109985,6412

[73 rows x 2 columns]

* 1. Resultados (subtotales, no forman parte de la jerarquía Grupo/Subgrupo/Cuenta):

In [10]:
Resultados = pd.Series(['Resultado de explotación', 'Resultado financiero',
                         'Resultado antes de impuestos', 'Resultado del ejercicio'])
print(Resultados)

0        Resultado de explotación
1            Resultado financiero
2    Resultado antes de impuestos
3         Resultado del ejercicio
dtype: str

In [11]:
# Borramos las filas de Resultado:
Ingresos = Ingresos[~Ingresos['Subcuenta'].isin(Resultados)]
# Borramos también las filas separadoras (Subcuenta vacía, Valor = 0):
Ingresos = Ingresos[~Ingresos['Subcuenta'].isna()]

In [12]:
Ingresos

                                            Subcuenta         Valor
5             1. Importe neto de la cifra de negocios   3268788,014
6                        b) Prestaciones de servicios   3268788,014
7                70500000 - PRESTACIONES DE SERVICIOS   3268788,014
9                               4. Aprovisionamientos  -849222,7309
10          c) Trabajos realizados por otras empresas  -849222,7309
11           60700000 - TRABAJOS REALIZADOS POR OTRAS  -849222,7309
13                              6. Gastos de personal  -217464,4149
14                  a) Sueldos, salarios y asimilados  -200840,0112
15                      64000000 - SUELDOS Y SALARIOS  -200840,0112
16                                 b) Cargos sociales  -16624,40371
17          64200000 - SEGURIDAD SOCIAL A CARGO DE LA  -16624,40371
19                     7. Otros gastos de explotación  -1877073,634
20                            a) Servicios exteriores  -1648052,895
21           62300000 - SERVICIOS PROFESIONALES INDEP  -268917,6166
22                             62400000 - TRANSPORTES   -744,785965
23                 62500001 - SEGURO DE VIDA SABADELL    -1047,3785
24            62600001 - Servicios bancarios SABADELL  -1002944,625
25              62600002 - Servicios bancarios BANKIA   -3767,71577
26                62600003 - Servicios bancarios BBVA    -319,43982
27          62600006 - Servicios Bancarios Coinmotion     -175,9086
28             62600007 - SERVICIOS BANCARIOS TITANES  -361411,3358
29              62700000 - PUBLICID PROPAGANDA Y RRPP   -6626,27301
30                         62900000 - OTROS SERVICIOS   -2097,81628
31  c) Pérdida, deteriorio y variación de provisio...  -229020,7388
32  69400001 - PROVISION DE PERDIDAS POR OPERACION...        -63735
33              69590000 - DOTA A LA PROVI OTROPCOMER  -165285,7388
35                   8. Amortización del inmovilizado  -168081,4109
36                      Amortización del inmovilizado  -168081,4109
37                      68060001 - DOTAMORT CASH LESS     -166560,8
38            68160001 - DOTAMORT5 SILLAS ERGONOMICAS      -191,205
39                68160002 - DOTAMORT5 MESAS OFICDEMI    -123,00855
40                 68160003 - DOTAMORT5 CAJONERAS NIX    -110,68645
41            68160004 - DOTAMORT4 ARCHIVADORES CARIN     -169,1102
42                 68160005 - DOTAMORT6 ARCHIV BISLEY     -174,6339
43                68160006 - DOTAMORT2 ARMARIOS CAPSA      -81,1559
44         68170001 - DOTAMORT DE APPLE MACBOOK P_RLH    -520,79993
45          68170002 - DOTAMORT DE SAMSUNG GALAXY_RLH   -150,010945
47                               13. Otros resultados    154,727335
48                          a) Ingresos excepcionales    154,727335
49                  77800000 - INGRESOS EXCEPCIONALES    154,727335
53                           14. Ingresos financieros       26,7687
54  b) De valores negociables y de créditos del ac...       26,7687
55              76900000 - OTROS INGRESOS FINANCIEROS       26,7687
57                             15. Gastos financieros    -886,08646
58                         b) Por deudas con terceros    -886,08646
59                       66230001 - PRESTAMO SABADELL    -886,08646
61  16. Variación de valor razonable en instrument...      90,33374
62                  a) Cartera de negociación y otros      90,33374
63          76300000 - BENEFICIOS DE CARTERA DE NEGOC      90,33374
65                          17. Diferencias de cambio  -9684,044615
66                              Diferencias de cambio  -9684,044615
67          66800000 - DIFERENCIAS NEGATIVAS DE CAMBI  -9684,044615
73                     19. Impuestos sobre beneficios   -36661,8804
74                         Impuestos sobre beneficios   -36661,8804
75                      63000000 - IMPUESTO CORRIENTE   -36661,8804

* 2. Grupo:

In [13]:
Grupo_id = pd.Series(['1.', '2.', '3.', '4.', '5.', '6.', '7.', '8.', '9.', '10.',
                       '11.', '12.', '13.', '14.', '15.', '16.', '17.', '18.', '19.', '20.'])
print(Grupo_id)

0      1.
1      2.
2      3.
3      4.
4      5.
5      6.
6      7.
7      8.
8      9.
9     10.
10    11.
11    12.
12    13.
13    14.
14    15.
15    16.
16    17.
17    18.
18    19.
19    20.
dtype: str

In [14]:
Grupo_id = Grupo_id.tolist()

In [15]:
# Para crear columna Grupo:
Ingresos['Grupo'] = Ingresos['Subcuenta'].where(Ingresos['Subcuenta'].str.startswith(tuple(Grupo_id))).ffill()
# Para Borrar Filas Grupo Original:
Ingresos = Ingresos[~Ingresos['Subcuenta'].str.startswith(tuple(Grupo_id))]

In [16]:
Ingresos

,Subcuenta,Valor,Grupo
6,b) Prestaciones de servicios,"3268788,014",1. Importe neto de la cifra de negocios
7,70500000 - PRESTACIONES DE SERVICIOS,"3268788,014",1. Importe neto de la cifra de negocios
10,c) Trabajos realizados por otras empresas,"-849222,7309",4. Aprovisionamientos
11,60700000 - TRABAJOS REALIZADOS POR OTRAS,"-849222,7309",4. Aprovisionamientos
14,"a) Sueldos, salarios y asimilados","-200840,0112",6. Gastos de personal
15,64000000 - SUELDOS Y SALARIOS,"-200840,0112",6. Gastos de personal
16,b) Cargos sociales,"-16624,40371",6. Gastos de personal
17,64200000 - SEGURIDAD SOCIAL A CARGO DE LA,"-16624,40371",6. Gastos de personal
20,a) Servicios exteriores,"-1648052,895",7. Otros gastos de explotación
21,62300000 - SERVICIOS PROFESIONALES INDEP,"-268917,6166",7. Otros gastos de explotación
22,62400000 - TRANSPORTES,"-744,785965",7. Otros gastos de explotación
23,62500001 - SEGURO DE VIDA SABADELL,"-1047,3785",7. Otros gastos de explotación
24,62600001 - Servicios bancarios SABADELL,"-1002944,625",7. Otros gastos de explotación
25,62600002 - Servicios bancarios BANKIA,"-3767,71577",7. Otros gastos de explotación
26,62600003 - Servicios bancarios BBVA,"-319,43982",7. Otros gastos de explotación
27,62600006 - Servicios Bancarios Coinmotion,"-175,9086",7. Otros gastos de explotación
28,62600007 - SERVICIOS BANCARIOS TITANES,"-361411,3358",7. Otros gastos de explotación
29,62700000 - PUBLICID PROPAGANDA Y RRPP,"-6626,27301",7. Otros gastos de explotación
30,62900000 - OTROS SERVICIOS,"-2097,81628",7. Otros gastos de explotación
31,"c) Pérdida, deteriorio y variación de provisio...","-229020,7388",7. Otros gastos de explotación
32,69400001 - PROVISION DE PERDIDAS POR OPERACION...,-63735,7. Otros gastos de explotación
33,69590000 - DOTA A LA PROVI OTROPCOMER,"-165285,7388",7. Otros gastos de explotación
36,Amortización del inmovilizado,"-168081,4109",8. Amortización del inmovilizado
37,68060001 - DOTAMORT CASH LESS,"-166560,8",8. Amortización del inmovilizado
38,68160001 - DOTAMORT5 SILLAS ERGONOMICAS,"-191,205",8. Amortización del inmovilizado
39,68160002 - DOTAMORT5 MESAS OFICDEMI,"-123,00855",8. Amortización del inmovilizado
40,68160003 - DOTAMORT5 CAJONERAS NIX,"-110,68645",8. Amortización del inmovilizado
41,68160004 - DOTAMORT4 ARCHIVADORES CARIN,"-169,1102",8. Amortización del inmovilizado
42,68160005 - DOTAMORT6 ARCHIV BISLEY,"-174,6339",8. Amortización del inmovilizado
43,68160006 - DOTAMORT2 ARMARIOS CAPSA,"-81,1559",8. Amortización del inmovilizado
44,68170001 - DOTAMORT DE APPLE MACBOOK P_RLH,"-520,79993",8. Amortización del inmovilizado
45,68170002 - DOTAMORT DE SAMSUNG GALAXY_RLH,"-150,010945",8. Amortización del inmovilizado
48,a) Ingresos excepcionales,"154,727335",13. Otros resultados
49,77800000 - INGRESOS EXCEPCIONALES,"154,727335",13. Otros resultados
54,b) De valores negociables y de créditos del ac...,"26,7687",14. Ingresos financieros
55,76900000 - OTROS INGRESOS FINANCIEROS,"26,7687",14. Ingresos financieros
58,b) Por deudas con terceros,"-886,08646",15. Gastos financieros
59,66230001 - PRESTAMO SABADELL,"-886,08646",15. Gastos financieros
62,a) Cartera de negociación y otros,"90,33374",16. Variación de valor razonable en instrument...
63,76300000 - BENEFICIOS DE CARTERA DE NEGOC,"90,33374",16. Variación de valor razonable en instrument...
66,Diferencias de cambio,"-9684,044615",17. Diferencias de cambio
67,66800000 - DIFERENCIAS NEGATIVAS DE CAMBI,"-9684,044615",17. Diferencias de cambio
74,Impuestos sobre beneficios,"-36661,8804",19. Impuestos sobre beneficios
75,63000000 - IMPUESTO CORRIENTE,"-36661,8804",19. Impuestos sobre beneficios

* Subgrupo:

In [17]:
# Holded no antepone letra cuando el Grupo solo tiene un único Subgrupo (ej: "Amortización 
# del inmovilizado", "Diferencias de cambio"). Normalizamos esas filas añadiendo "a) " 
# para que sigan el mismo patrón que el resto:
Subgrupos_sin_letra = pd.Series(['Amortización del inmovilizado', 'Diferencias de cambio',
                                  'Impuestos sobre beneficios'])
print(Subgrupos_sin_letra)

0    Amortización del inmovilizado
1            Diferencias de cambio
2       Impuestos sobre beneficios
dtype: str

In [18]:
Ingresos['Subcuenta'] = Ingresos['Subcuenta'].mask(Ingresos['Subcuenta'].isin(Subgrupos_sin_letra),
                                                     'a) ' + Ingresos['Subcuenta'])

In [19]:
Ingresos

,Subcuenta,Valor,Grupo
6,b) Prestaciones de servicios,"3268788,014",1. Importe neto de la cifra de negocios
7,70500000 - PRESTACIONES DE SERVICIOS,"3268788,014",1. Importe neto de la cifra de negocios
10,c) Trabajos realizados por otras empresas,"-849222,7309",4. Aprovisionamientos
11,60700000 - TRABAJOS REALIZADOS POR OTRAS,"-849222,7309",4. Aprovisionamientos
14,"a) Sueldos, salarios y asimilados","-200840,0112",6. Gastos de personal
15,64000000 - SUELDOS Y SALARIOS,"-200840,0112",6. Gastos de personal
16,b) Cargos sociales,"-16624,40371",6. Gastos de personal
17,64200000 - SEGURIDAD SOCIAL A CARGO DE LA,"-16624,40371",6. Gastos de personal
20,a) Servicios exteriores,"-1648052,895",7. Otros gastos de explotación
21,62300000 - SERVICIOS PROFESIONALES INDEP,"-268917,6166",7. Otros gastos de explotación
22,62400000 - TRANSPORTES,"-744,785965",7. Otros gastos de explotación
23,62500001 - SEGURO DE VIDA SABADELL,"-1047,3785",7. Otros gastos de explotación
24,62600001 - Servicios bancarios SABADELL,"-1002944,625",7. Otros gastos de explotación
25,62600002 - Servicios bancarios BANKIA,"-3767,71577",7. Otros gastos de explotación
26,62600003 - Servicios bancarios BBVA,"-319,43982",7. Otros gastos de explotación
27,62600006 - Servicios Bancarios Coinmotion,"-175,9086",7. Otros gastos de explotación
28,62600007 - SERVICIOS BANCARIOS TITANES,"-361411,3358",7. Otros gastos de explotación
29,62700000 - PUBLICID PROPAGANDA Y RRPP,"-6626,27301",7. Otros gastos de explotación
30,62900000 - OTROS SERVICIOS,"-2097,81628",7. Otros gastos de explotación
31,"c) Pérdida, deteriorio y variación de provisio...","-229020,7388",7. Otros gastos de explotación
32,69400001 - PROVISION DE PERDIDAS POR OPERACION...,-63735,7. Otros gastos de explotación
33,69590000 - DOTA A LA PROVI OTROPCOMER,"-165285,7388",7. Otros gastos de explotación
36,a) Amortización del inmovilizado,"-168081,4109",8. Amortización del inmovilizado
37,68060001 - DOTAMORT CASH LESS,"-166560,8",8. Amortización del inmovilizado
38,68160001 - DOTAMORT5 SILLAS ERGONOMICAS,"-191,205",8. Amortización del inmovilizado
39,68160002 - DOTAMORT5 MESAS OFICDEMI,"-123,00855",8. Amortización del inmovilizado
40,68160003 - DOTAMORT5 CAJONERAS NIX,"-110,68645",8. Amortización del inmovilizado
41,68160004 - DOTAMORT4 ARCHIVADORES CARIN,"-169,1102",8. Amortización del inmovilizado
42,68160005 - DOTAMORT6 ARCHIV BISLEY,"-174,6339",8. Amortización del inmovilizado
43,68160006 - DOTAMORT2 ARMARIOS CAPSA,"-81,1559",8. Amortización del inmovilizado
44,68170001 - DOTAMORT DE APPLE MACBOOK P_RLH,"-520,79993",8. Amortización del inmovilizado
45,68170002 - DOTAMORT DE SAMSUNG GALAXY_RLH,"-150,010945",8. Amortización del inmovilizado
48,a) Ingresos excepcionales,"154,727335",13. Otros resultados
49,77800000 - INGRESOS EXCEPCIONALES,"154,727335",13. Otros resultados
54,b) De valores negociables y de créditos del ac...,"26,7687",14. Ingresos financieros
55,76900000 - OTROS INGRESOS FINANCIEROS,"26,7687",14. Ingresos financieros
58,b) Por deudas con terceros,"-886,08646",15. Gastos financieros
59,66230001 - PRESTAMO SABADELL,"-886,08646",15. Gastos financieros
62,a) Cartera de negociación y otros,"90,33374",16. Variación de valor razonable en instrument...
63,76300000 - BENEFICIOS DE CARTERA DE NEGOC,"90,33374",16. Variación de valor razonable en instrument...
66,a) Diferencias de cambio,"-9684,044615",17. Diferencias de cambio
67,66800000 - DIFERENCIAS NEGATIVAS DE CAMBI,"-9684,044615",17. Diferencias de cambio
74,a) Impuestos sobre beneficios,"-36661,8804",19. Impuestos sobre beneficios
75,63000000 - IMPUESTO CORRIENTE,"-36661,8804",19. Impuestos sobre beneficios

In [20]:
Subgrupo_id = pd.Series(['a)', 'b)', 'c)', 'd)', 'e)', 'f)', 'g)']).tolist()

In [21]:
# Creamos columna Subgrupo:
Ingresos['SubGrupo'] = Ingresos['Subcuenta'].where(Ingresos['Subcuenta'].str.startswith(tuple(Subgrupo_id))).ffill()
# Eliminamos columna original con Subgrupo:
Ingresos = Ingresos[~Ingresos['Subcuenta'].str.startswith(tuple(Subgrupo_id))]

In [22]:
Ingresos

,Subcuenta,Valor,Grupo,SubGrupo
7,70500000 - PRESTACIONES DE SERVICIOS,"3268788,014",1. Importe neto de la cifra de negocios,b) Prestaciones de servicios
11,60700000 - TRABAJOS REALIZADOS POR OTRAS,"-849222,7309",4. Aprovisionamientos,c) Trabajos realizados por otras empresas
15,64000000 - SUELDOS Y SALARIOS,"-200840,0112",6. Gastos de personal,"a) Sueldos, salarios y asimilados"
17,64200000 - SEGURIDAD SOCIAL A CARGO DE LA,"-16624,40371",6. Gastos de personal,b) Cargos sociales
21,62300000 - SERVICIOS PROFESIONALES INDEP,"-268917,6166",7. Otros gastos de explotación,a) Servicios exteriores
22,62400000 - TRANSPORTES,"-744,785965",7. Otros gastos de explotación,a) Servicios exteriores
23,62500001 - SEGURO DE VIDA SABADELL,"-1047,3785",7. Otros gastos de explotación,a) Servicios exteriores
24,62600001 - Servicios bancarios SABADELL,"-1002944,625",7. Otros gastos de explotación,a) Servicios exteriores
25,62600002 - Servicios bancarios BANKIA,"-3767,71577",7. Otros gastos de explotación,a) Servicios exteriores
26,62600003 - Servicios bancarios BBVA,"-319,43982",7. Otros gastos de explotación,a) Servicios exteriores
27,62600006 - Servicios Bancarios Coinmotion,"-175,9086",7. Otros gastos de explotación,a) Servicios exteriores
28,62600007 - SERVICIOS BANCARIOS TITANES,"-361411,3358",7. Otros gastos de explotación,a) Servicios exteriores
29,62700000 - PUBLICID PROPAGANDA Y RRPP,"-6626,27301",7. Otros gastos de explotación,a) Servicios exteriores
30,62900000 - OTROS SERVICIOS,"-2097,81628",7. Otros gastos de explotación,a) Servicios exteriores
32,69400001 - PROVISION DE PERDIDAS POR OPERACION...,-63735,7. Otros gastos de explotación,"c) Pérdida, deteriorio y variación de provisio..."
33,69590000 - DOTA A LA PROVI OTROPCOMER,"-165285,7388",7. Otros gastos de explotación,"c) Pérdida, deteriorio y variación de provisio..."
37,68060001 - DOTAMORT CASH LESS,"-166560,8",8. Amortización del inmovilizado,a) Amortización del inmovilizado
38,68160001 - DOTAMORT5 SILLAS ERGONOMICAS,"-191,205",8. Amortización del inmovilizado,a) Amortización del inmovilizado
39,68160002 - DOTAMORT5 MESAS OFICDEMI,"-123,00855",8. Amortización del inmovilizado,a) Amortización del inmovilizado
40,68160003 - DOTAMORT5 CAJONERAS NIX,"-110,68645",8. Amortización del inmovilizado,a) Amortización del inmovilizado
41,68160004 - DOTAMORT4 ARCHIVADORES CARIN,"-169,1102",8. Amortización del inmovilizado,a) Amortización del inmovilizado
42,68160005 - DOTAMORT6 ARCHIV BISLEY,"-174,6339",8. Amortización del inmovilizado,a) Amortización del inmovilizado
43,68160006 - DOTAMORT2 ARMARIOS CAPSA,"-81,1559",8. Amortización del inmovilizado,a) Amortización del inmovilizado
44,68170001 - DOTAMORT DE APPLE MACBOOK P_RLH,"-520,79993",8. Amortización del inmovilizado,a) Amortización del inmovilizado
45,68170002 - DOTAMORT DE SAMSUNG GALAXY_RLH,"-150,010945",8. Amortización del inmovilizado,a) Amortización del inmovilizado
49,77800000 - INGRESOS EXCEPCIONALES,"154,727335",13. Otros resultados,a) Ingresos excepcionales
55,76900000 - OTROS INGRESOS FINANCIEROS,"26,7687",14. Ingresos financieros,b) De valores negociables y de créditos del ac...
59,66230001 - PRESTAMO SABADELL,"-886,08646",15. Gastos financieros,b) Por deudas con terceros
63,76300000 - BENEFICIOS DE CARTERA DE NEGOC,"90,33374",16. Variación de valor razonable en instrument...,a) Cartera de negociación y otros
67,66800000 - DIFERENCIAS NEGATIVAS DE CAMBI,"-9684,044615",17. Diferencias de cambio,a) Diferencias de cambio
75,63000000 - IMPUESTO CORRIENTE,"-36661,8804",19. Impuestos sobre beneficios,a) Impuestos sobre beneficios

* Cuenta: lo que queda son las cuentas hoja (código + " - " + descripción)

In [23]:
print(Ingresos)

                                            Subcuenta         Valor  \
7                70500000 - PRESTACIONES DE SERVICIOS   3268788,014
11           60700000 - TRABAJOS REALIZADOS POR OTRAS  -849222,7309
15                      64000000 - SUELDOS Y SALARIOS  -200840,0112
17          64200000 - SEGURIDAD SOCIAL A CARGO DE LA  -16624,40371
21           62300000 - SERVICIOS PROFESIONALES INDEP  -268917,6166
22                             62400000 - TRANSPORTES   -744,785965
23                 62500001 - SEGURO DE VIDA SABADELL    -1047,3785
24            62600001 - Servicios bancarios SABADELL  -1002944,625
25              62600002 - Servicios bancarios BANKIA   -3767,71577
26                62600003 - Servicios bancarios BBVA    -319,43982
27          62600006 - Servicios Bancarios Coinmotion     -175,9086
28             62600007 - SERVICIOS BANCARIOS TITANES  -361411,3358
29              62700000 - PUBLICID PROPAGANDA Y RRPP   -6626,27301
30                         62900000 - OTROS SERVICIOS   -2097,81628
32  69400001 - PROVISION DE PERDIDAS POR OPERACION...        -63735
33              69590000 - DOTA A LA PROVI OTROPCOMER  -165285,7388
37                      68060001 - DOTAMORT CASH LESS     -166560,8
38            68160001 - DOTAMORT5 SILLAS ERGONOMICAS      -191,205
39                68160002 - DOTAMORT5 MESAS OFICDEMI    -123,00855
40                 68160003 - DOTAMORT5 CAJONERAS NIX    -110,68645
41            68160004 - DOTAMORT4 ARCHIVADORES CARIN     -169,1102
42                 68160005 - DOTAMORT6 ARCHIV BISLEY     -174,6339
43                68160006 - DOTAMORT2 ARMARIOS CAPSA      -81,1559
44         68170001 - DOTAMORT DE APPLE MACBOOK P_RLH    -520,79993
45          68170002 - DOTAMORT DE SAMSUNG GALAXY_RLH   -150,010945
49                  77800000 - INGRESOS EXCEPCIONALES    154,727335
55              76900000 - OTROS INGRESOS FINANCIEROS       26,7687
59                       66230001 - PRESTAMO SABADELL    -886,08646
63          76300000 - BENEFICIOS DE CARTERA DE NEGOC      90,33374
67          66800000 - DIFERENCIAS NEGATIVAS DE CAMBI  -9684,044615
75                      63000000 - IMPUESTO CORRIENTE   -36661,8804

                                                Grupo  \
7             1. Importe neto de la cifra de negocios
11                              4. Aprovisionamientos
15                              6. Gastos de personal
17                              6. Gastos de personal
21                     7. Otros gastos de explotación
22                     7. Otros gastos de explotación
23                     7. Otros gastos de explotación
24                     7. Otros gastos de explotación
25                     7. Otros gastos de explotación
26                     7. Otros gastos de explotación
27                     7. Otros gastos de explotación
28                     7. Otros gastos de explotación
29                     7. Otros gastos de explotación
30                     7. Otros gastos de explotación
32                     7. Otros gastos de explotación
33                     7. Otros gastos de explotación
37                   8. Amortización del inmovilizado
38                   8. Amortización del inmovilizado
39                   8. Amortización del inmovilizado
40                   8. Amortización del inmovilizado
41                   8. Amortización del inmovilizado
42                   8. Amortización del inmovilizado
43                   8. Amortización del inmovilizado
44                   8. Amortización del inmovilizado
45                   8. Amortización del inmovilizado
49                               13. Otros resultados
55                           14. Ingresos financieros
59                             15. Gastos financieros
63  16. Variación de valor razonable en instrument...
67                          17. Diferencias de cambio
75                     19. Impuestos sobre beneficios

                                             SubGrupo
7                        b) Prestaciones de servicios
11          c) Trabajos realizados por otras empresas
15                  a) Sueldos, salarios y asimilados
17                                 b) Cargos sociales
21                            a) Servicios exteriores
22                            a) Servicios exteriores
23                            a) Servicios exteriores
24                            a) Servicios exteriores
25                            a) Servicios exteriores
26                            a) Servicios exteriores
27                            a) Servicios exteriores
28                            a) Servicios exteriores
29                            a) Servicios exteriores
30                            a) Servicios exteriores
32  c) Pérdida, deteriorio y variación de provisio...
33  c) Pérdida, deteriorio y variación de provisio...
37                   a) Amortización del inmovilizado
38                   a) Amortización del inmovilizado
39                   a) Amortización del inmovilizado
40                   a) Amortización del inmovilizado
41                   a) Amortización del inmovilizado
42                   a) Amortización del inmovilizado
43                   a) Amortización del inmovilizado
44                   a) Amortización del inmovilizado
45                   a) Amortización del inmovilizado
49                          a) Ingresos excepcionales
55  b) De valores negociables y de créditos del ac...
59                         b) Por deudas con terceros
63                  a) Cartera de negociación y otros
67                           a) Diferencias de cambio
75                      a) Impuestos sobre beneficios

In [24]:
# Configuración Año y Periodo (Establecidos en el inicio del script)

Año = IncomeFile[8:12]

Ingresos['Año'] = Año
Ingresos['Periodo'] = Periodo

* Ordenar Columnas:

In [25]:
Ingresos = Ingresos[['Año', 'Periodo', 'Grupo', 'SubGrupo', 'Subcuenta', 'Valor']]

In [26]:
Ingresos

,Año,Periodo,Grupo,SubGrupo,Subcuenta,Valor
7,2020,Anual,1. Importe neto de la cifra de negocios,b) Prestaciones de servicios,70500000 - PRESTACIONES DE SERVICIOS,"3268788,014"
11,2020,Anual,4. Aprovisionamientos,c) Trabajos realizados por otras empresas,60700000 - TRABAJOS REALIZADOS POR OTRAS,"-849222,7309"
15,2020,Anual,6. Gastos de personal,"a) Sueldos, salarios y asimilados",64000000 - SUELDOS Y SALARIOS,"-200840,0112"
17,2020,Anual,6. Gastos de personal,b) Cargos sociales,64200000 - SEGURIDAD SOCIAL A CARGO DE LA,"-16624,40371"
21,2020,Anual,7. Otros gastos de explotación,a) Servicios exteriores,62300000 - SERVICIOS PROFESIONALES INDEP,"-268917,6166"
22,2020,Anual,7. Otros gastos de explotación,a) Servicios exteriores,62400000 - TRANSPORTES,"-744,785965"
23,2020,Anual,7. Otros gastos de explotación,a) Servicios exteriores,62500001 - SEGURO DE VIDA SABADELL,"-1047,3785"
24,2020,Anual,7. Otros gastos de explotación,a) Servicios exteriores,62600001 - Servicios bancarios SABADELL,"-1002944,625"
25,2020,Anual,7. Otros gastos de explotación,a) Servicios exteriores,62600002 - Servicios bancarios BANKIA,"-3767,71577"
26,2020,Anual,7. Otros gastos de explotación,a) Servicios exteriores,62600003 - Servicios bancarios BBVA,"-319,43982"
27,2020,Anual,7. Otros gastos de explotación,a) Servicios exteriores,62600006 - Servicios Bancarios Coinmotion,"-175,9086"
28,2020,Anual,7. Otros gastos de explotación,a) Servicios exteriores,62600007 - SERVICIOS BANCARIOS TITANES,"-361411,3358"
29,2020,Anual,7. Otros gastos de explotación,a) Servicios exteriores,62700000 - PUBLICID PROPAGANDA Y RRPP,"-6626,27301"
30,2020,Anual,7. Otros gastos de explotación,a) Servicios exteriores,62900000 - OTROS SERVICIOS,"-2097,81628"
32,2020,Anual,7. Otros gastos de explotación,"c) Pérdida, deteriorio y variación de provisio...",69400001 - PROVISION DE PERDIDAS POR OPERACION...,-63735
33,2020,Anual,7. Otros gastos de explotación,"c) Pérdida, deteriorio y variación de provisio...",69590000 - DOTA A LA PROVI OTROPCOMER,"-165285,7388"
37,2020,Anual,8. Amortización del inmovilizado,a) Amortización del inmovilizado,68060001 - DOTAMORT CASH LESS,"-166560,8"
38,2020,Anual,8. Amortización del inmovilizado,a) Amortización del inmovilizado,68160001 - DOTAMORT5 SILLAS ERGONOMICAS,"-191,205"
39,2020,Anual,8. Amortización del inmovilizado,a) Amortización del inmovilizado,68160002 - DOTAMORT5 MESAS OFICDEMI,"-123,00855"
40,2020,Anual,8. Amortización del inmovilizado,a) Amortización del inmovilizado,68160003 - DOTAMORT5 CAJONERAS NIX,"-110,68645"
41,2020,Anual,8. Amortización del inmovilizado,a) Amortización del inmovilizado,68160004 - DOTAMORT4 ARCHIVADORES CARIN,"-169,1102"
42,2020,Anual,8. Amortización del inmovilizado,a) Amortización del inmovilizado,68160005 - DOTAMORT6 ARCHIV BISLEY,"-174,6339"
43,2020,Anual,8. Amortización del inmovilizado,a) Amortización del inmovilizado,68160006 - DOTAMORT2 ARMARIOS CAPSA,"-81,1559"
44,2020,Anual,8. Amortización del inmovilizado,a) Amortización del inmovilizado,68170001 - DOTAMORT DE APPLE MACBOOK P_RLH,"-520,79993"
45,2020,Anual,8. Amortización del inmovilizado,a) Amortización del inmovilizado,68170002 - DOTAMORT DE SAMSUNG GALAXY_RLH,"-150,010945"
49,2020,Anual,13. Otros resultados,a) Ingresos excepcionales,77800000 - INGRESOS EXCEPCIONALES,"154,727335"
55,2020,Anual,14. Ingresos financieros,b) De valores negociables y de créditos del ac...,76900000 - OTROS INGRESOS FINANCIEROS,"26,7687"
59,2020,Anual,15. Gastos financieros,b) Por deudas con terceros,66230001 - PRESTAMO SABADELL,"-886,08646"
63,2020,Anual,16. Variación de valor razonable en instrument...,a) Cartera de negociación y otros,76300000 - BENEFICIOS DE CARTERA DE NEGOC,"90,33374"
67,2020,Anual,17. Diferencias de cambio,a) Diferencias de cambio,66800000 - DIFERENCIAS NEGATIVAS DE CAMBI,"-9684,044615"
75,2020,Anual,19. Impuestos sobre beneficios,a) Impuestos sobre beneficios,63000000 - IMPUESTO CORRIENTE,"-36661,8804"

* Pendiente Transformación: Desglosar Columnas correspondientes en {Id y Nombre}

In [27]:
# Division Columnas y creación columnas_id's: 

Ingresos[['Grupo_id', 'Grupo']] = Ingresos['Grupo'].str.split('. ', n = 1, expand = True)         # Grupo
Ingresos[['SubGrupo_id', 'SubGrupo']] = Ingresos['SubGrupo'].str.split(') ', n = 1, expand = True, regex = False) # SubGrupo
Ingresos[['Cuenta_id', 'Cuenta']] = Ingresos['Subcuenta'].str.split(' - ', n = 1, expand = True)   # Cuenta

In [28]:
Ingresos.head(5)

,Año,Periodo,Grupo,SubGrupo,Subcuenta,Valor,Grupo_id,SubGrupo_id,Cuenta_id,Cuenta
7,2020,Anual,Importe neto de la cifra de negocios,Prestaciones de servicios,70500000 - PRESTACIONES DE SERVICIOS,"3268788,014",1,b,70500000,PRESTACIONES DE SERVICIOS
11,2020,Anual,Aprovisionamientos,Trabajos realizados por otras empresas,60700000 - TRABAJOS REALIZADOS POR OTRAS,"-849222,7309",4,c,60700000,TRABAJOS REALIZADOS POR OTRAS
15,2020,Anual,Gastos de personal,"Sueldos, salarios y asimilados",64000000 - SUELDOS Y SALARIOS,"-200840,0112",6,a,64000000,SUELDOS Y SALARIOS
17,2020,Anual,Gastos de personal,Cargos sociales,64200000 - SEGURIDAD SOCIAL A CARGO DE LA,"-16624,40371",6,b,64200000,SEGURIDAD SOCIAL A CARGO DE LA
21,2020,Anual,Otros gastos de explotación,Servicios exteriores,62300000 - SERVICIOS PROFESIONALES INDEP,"-268917,6166",7,a,62300000,SERVICIOS PROFESIONALES INDEP

In [29]:
Ingresos.columns

Index(['Año', 'Periodo', 'Grupo', 'SubGrupo', 'Subcuenta', 'Valor', 'Grupo_id',
       'SubGrupo_id', 'Cuenta_id', 'Cuenta'],
      dtype='str')

In [30]:
# Ordenamos el dataframe: 
Ingresos = Ingresos[['Año', 'Grupo_id', 'Grupo', 'SubGrupo_id', 'SubGrupo',
                      'Cuenta_id', 'Cuenta', 'Valor']]

In [31]:
# Cambiamos tipo de dato de Valor de Object a Numeric:
Ingresos['Valor'] = Ingresos['Valor'].str.replace('.', '', regex=False)   # Elimina los puntos que separan miles
Ingresos['Valor'] = Ingresos['Valor'].str.replace(',', '.', regex=False)  # Reemplaza las comas por puntos decimales
Ingresos['Valor'] = pd.to_numeric(Ingresos['Valor'], errors='coerce')

In [32]:
# Creamos columna Valores Absolutos:
Ingresos['Abs Valor'] = Ingresos['Valor'].abs()

In [33]:
# Renombramos columnas finales para que coincidan con el resto de reportes:
Ingresos = Ingresos.rename(columns={'Grupo_id': 'ID Grupo', 'SubGrupo_id': 'ID Subgrupo',
                                     'Cuenta_id': 'ID Cuenta', 'Valor': 'Valores', 'Abs Valor': 'Abs Valores'})
Ingresos['ID Grupo'] = pd.to_numeric(Ingresos['ID Grupo'])

In [34]:
Ingresos.head(10)

,Año,ID Grupo,Grupo,ID Subgrupo,SubGrupo,ID Cuenta,Cuenta,Valores,Abs Valores
7,2020,1,Importe neto de la cifra de negocios,b,Prestaciones de servicios,70500000,PRESTACIONES DE SERVICIOS,3.268788e+06,3.268788e+06
11,2020,4,Aprovisionamientos,c,Trabajos realizados por otras empresas,60700000,TRABAJOS REALIZADOS POR OTRAS,-8.492227e+05,8.492227e+05
15,2020,6,Gastos de personal,a,"Sueldos, salarios y asimilados",64000000,SUELDOS Y SALARIOS,-2.008400e+05,2.008400e+05
17,2020,6,Gastos de personal,b,Cargos sociales,64200000,SEGURIDAD SOCIAL A CARGO DE LA,-1.662440e+04,1.662440e+04
21,2020,7,Otros gastos de explotación,a,Servicios exteriores,62300000,SERVICIOS PROFESIONALES INDEP,-2.689176e+05,2.689176e+05
22,2020,7,Otros gastos de explotación,a,Servicios exteriores,62400000,TRANSPORTES,-7.447860e+02,7.447860e+02
23,2020,7,Otros gastos de explotación,a,Servicios exteriores,62500001,SEGURO DE VIDA SABADELL,-1.047379e+03,1.047379e+03
24,2020,7,Otros gastos de explotación,a,Servicios exteriores,62600001,Servicios bancarios SABADELL,-1.002945e+06,1.002945e+06
25,2020,7,Otros gastos de explotación,a,Servicios exteriores,62600002,Servicios bancarios BANKIA,-3.767716e+03,3.767716e+03
26,2020,7,Otros gastos de explotación,a,Servicios exteriores,62600003,Servicios bancarios BBVA,-3.194398e+02,3.194398e+02

### Resultado y Descarga:

In [35]:
Ingresos.head(4)

,Año,ID Grupo,Grupo,ID Subgrupo,SubGrupo,ID Cuenta,Cuenta,Valores,Abs Valores
7,2020,1,Importe neto de la cifra de negocios,b,Prestaciones de servicios,70500000,PRESTACIONES DE SERVICIOS,3.268788e+06,3.268788e+06
11,2020,4,Aprovisionamientos,c,Trabajos realizados por otras empresas,60700000,TRABAJOS REALIZADOS POR OTRAS,-8.492227e+05,8.492227e+05
15,2020,6,Gastos de personal,a,"Sueldos, salarios y asimilados",64000000,SUELDOS Y SALARIOS,-2.008400e+05,2.008400e+05
17,2020,6,Gastos de personal,b,Cargos sociales,64200000,SEGURIDAD SOCIAL A CARGO DE LA,-1.662440e+04,1.662440e+04

In [36]:
### Descarga arhivo: 
NombreArchivo = f"File.Income{Año}.csv"
Ingresos.to_csv(NombreArchivo, index=False)

In [37]:
f"Archivo creado llamado: 'File.Income{Año}.csv'"

"Archivo creado llamado: 'File.Income2020.csv'"