In [1]:
# Selecciona Balance y Período para descargar: 
BalanceFile = "Balance2024.csv"
Periodo = 'Anual' # 'Anual' si es Balance del Año. 'Q1'..'Q4' si es Trimestral.

### Tranformación Automatizada Datos Holded:

In [2]:
import pandas as pd 
import numpy as np

In [3]:
# Importamos data:
    # BalanceFile = "Balance2022.csv"
    # Periodo = 'Anual'

Balance = pd.read_csv(f"/home/claude/holded/HoldedFiles/{BalanceFile}", header = None, sep = '\t')

In [4]:
# Renombramos nombres de columnas:
Balance = Balance.rename(columns={0 : 'Subcuenta', 1 : 'Valor'})

* 1. Partida:

In [5]:
# Creamos columna con el nombre de la partida:
Balance['Partida'] = Balance['Subcuenta'].where(Balance['Valor'].isna()).ffill()
# Borrar fila original donde Valor es NaN:
Balance = Balance[~Balance['Valor'].isna()]

In [6]:
Balance

,Subcuenta,Valor,Partida
1,Activo No Corriente,"158121,9386",ACTIVO
2,I. Inmovilizado intangible,"71311,58042",ACTIVO
3,5. Aplicaciones informáticas,"71311,58042",ACTIVO
4,206 Aplicaciones informáticas,"923003,2",ACTIVO
5,20600001 - CASH LESS DESARROLLO SOFTWARE,"923003,2",ACTIVO
...,...,...,...
121,4709 Hacienda Pública,"8171,91",5. Activos por impuesto corriente
141,572 Bancos,"680354,50",1. Tesorería
214,4750 Hacienda Pública,"33167,95",6. Otras deudas con las Administraciones Públicas
216,4751 Hacienda Pública,"34462,54",47500000 - HACIENDA PÚBLICA ACREEDORA PO
219,476 Organismos de la Seguridad Social,"12845,25",47510001 - HP ACREED RETEN TRABAJADOR

* 2. Subpartida:

In [7]:
Subpartidas = pd.Series(['Activo No Corriente', 'Activo Corriente', 'Patrimonio Neto',
                       'Pasivo Corriente', 'Pasivo No Corriente'])
print(Subpartidas)

0    Activo No Corriente
1       Activo Corriente
2        Patrimonio Neto
3       Pasivo Corriente
4    Pasivo No Corriente
dtype: str

In [8]:
# 1. Creamos columna para filas con Subpartidas:
Balance['Subpartida'] = Balance['Subcuenta'].where(Balance['Subcuenta'].isin(Subpartidas)).ffill()
# 2. Eliminamos la columna con Subpartida Original:
Balance = Balance[~Balance['Subcuenta'].isin(Subpartidas)]

In [9]:
Balance

,Subcuenta,Valor,Partida,Subpartida
2,I. Inmovilizado intangible,"71311,58042",ACTIVO,Activo No Corriente
3,5. Aplicaciones informáticas,"71311,58042",ACTIVO,Activo No Corriente
4,206 Aplicaciones informáticas,"923003,2",ACTIVO,Activo No Corriente
5,20600001 - CASH LESS DESARROLLO SOFTWARE,"923003,2",ACTIVO,Activo No Corriente
6,2806 Amortización acumulada de aplicaciones in...,"-851691,6196",ACTIVO,Activo No Corriente
...,...,...,...,...
121,4709 Hacienda Pública,"8171,91",5. Activos por impuesto corriente,Activo No Corriente
141,572 Bancos,"680354,50",1. Tesorería,Activo No Corriente
214,4750 Hacienda Pública,"33167,95",6. Otras deudas con las Administraciones Públicas,Activo No Corriente
216,4751 Hacienda Pública,"34462,54",47500000 - HACIENDA PÚBLICA ACREEDORA PO,Activo No Corriente
219,476 Organismos de la Seguridad Social,"12845,25",47510001 - HP ACREED RETEN TRABAJADOR,Activo No Corriente

* 3. Grupo:

In [10]:
Grupo_id = pd.Series(['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX', 'X'])

In [11]:
Grupo_id = Grupo_id.tolist()

In [12]:
# Para crear columna Grupo:
Balance['Grupo'] = Balance['Subcuenta'].where(Balance['Subcuenta'].str.startswith(tuple(Grupo_id))).ffill()
# Para Borrar Filas Grupo Original:
Balance = Balance[~Balance['Subcuenta'].str.startswith(tuple(Grupo_id))]

In [13]:
Balance

,Subcuenta,Valor,Partida,Subpartida,Grupo
3,5. Aplicaciones informáticas,"71311,58042",ACTIVO,Activo No Corriente,I. Inmovilizado intangible
4,206 Aplicaciones informáticas,"923003,2",ACTIVO,Activo No Corriente,I. Inmovilizado intangible
5,20600001 - CASH LESS DESARROLLO SOFTWARE,"923003,2",ACTIVO,Activo No Corriente,I. Inmovilizado intangible
6,2806 Amortización acumulada de aplicaciones in...,"-851691,6196",ACTIVO,Activo No Corriente,I. Inmovilizado intangible
7,28060001 - AMORTACUMCASH LESS,"-851691,6196",ACTIVO,Activo No Corriente,I. Inmovilizado intangible
...,...,...,...,...,...
121,4709 Hacienda Pública,"8171,91",5. Activos por impuesto corriente,Activo No Corriente,VI. Activos por impuesto diferido
141,572 Bancos,"680354,50",1. Tesorería,Activo No Corriente,VI. Activos por impuesto diferido
214,4750 Hacienda Pública,"33167,95",6. Otras deudas con las Administraciones Públicas,Activo No Corriente,VI. Activos por impuesto diferido
216,4751 Hacienda Pública,"34462,54",47500000 - HACIENDA PÚBLICA ACREEDORA PO,Activo No Corriente,VI. Activos por impuesto diferido
219,476 Organismos de la Seguridad Social,"12845,25",47510001 - HP ACREED RETEN TRABAJADOR,Activo No Corriente,VI. Activos por impuesto diferido

* Subgrupo:

In [14]:
Subgrupo_id = pd.Series(['1.', '2.', '3.', '4.', '5.', '6.', '7.',
                         '8.', '9.']).tolist()

In [15]:
# Creamos columna Subgrupo:
Balance['SubGrupo'] = Balance['Subcuenta'].where(Balance['Subcuenta'].str.startswith(tuple(Subgrupo_id))).ffill()
# Eliminamos columna original con Subgrupo:
Balance = Balance[~Balance['Subcuenta'].str.startswith(tuple(Subgrupo_id))]

In [16]:
Balance

,Subcuenta,Valor,Partida,Subpartida,Grupo,SubGrupo
4,206 Aplicaciones informáticas,"923003,2",ACTIVO,Activo No Corriente,I. Inmovilizado intangible,5. Aplicaciones informáticas
5,20600001 - CASH LESS DESARROLLO SOFTWARE,"923003,2",ACTIVO,Activo No Corriente,I. Inmovilizado intangible,5. Aplicaciones informáticas
6,2806 Amortización acumulada de aplicaciones in...,"-851691,6196",ACTIVO,Activo No Corriente,I. Inmovilizado intangible,5. Aplicaciones informáticas
7,28060001 - AMORTACUMCASH LESS,"-851691,6196",ACTIVO,Activo No Corriente,I. Inmovilizado intangible,5. Aplicaciones informáticas
10,216 Mobiliario,"27302,08147",ACTIVO,Activo No Corriente,II. Inmovilizado material,2. Instalaciones técnicas y otro inmovilizado ...
...,...,...,...,...,...,...
121,4709 Hacienda Pública,"8171,91",5. Activos por impuesto corriente,Activo No Corriente,VI. Activos por impuesto diferido,5. Otros activos financieros
141,572 Bancos,"680354,50",1. Tesorería,Activo No Corriente,VI. Activos por impuesto diferido,5. Otros activos financieros
214,4750 Hacienda Pública,"33167,95",6. Otras deudas con las Administraciones Públicas,Activo No Corriente,VI. Activos por impuesto diferido,5. Otros activos financieros
216,4751 Hacienda Pública,"34462,54",47500000 - HACIENDA PÚBLICA ACREEDORA PO,Activo No Corriente,VI. Activos por impuesto diferido,5. Otros activos financieros
219,476 Organismos de la Seguridad Social,"12845,25",47510001 - HP ACREED RETEN TRABAJADOR,Activo No Corriente,VI. Activos por impuesto diferido,5. Otros activos financieros

* Cuenta:

In [17]:
print(Balance)

                                             Subcuenta         Valor  \
4                        206 Aplicaciones informáticas      923003,2
5             20600001 - CASH LESS DESARROLLO SOFTWARE      923003,2
6    2806 Amortización acumulada de aplicaciones in...  -851691,6196
7                        28060001 - AMORTACUMCASH LESS  -851691,6196
10                                      216 Mobiliario   27302,08147
..                                                 ...           ...
121                              4709 Hacienda Pública       8171,91
141                                         572 Bancos     680354,50
214                              4750 Hacienda Pública      33167,95
216                              4751 Hacienda Pública      34462,54
219              476 Organismos de la Seguridad Social      12845,25

                                               Partida           Subpartida  \
4                                               ACTIVO  Activo No Corriente
5                                               ACTIVO  Activo No Corriente
6                                               ACTIVO  Activo No Corriente
7                                               ACTIVO  Activo No Corriente
10                                              ACTIVO  Activo No Corriente
..                                                 ...                  ...
121                  5. Activos por impuesto corriente  Activo No Corriente
141                                       1. Tesorería  Activo No Corriente
214  6. Otras deudas con las Administraciones Públicas  Activo No Corriente
216           47500000 - HACIENDA PÚBLICA ACREEDORA PO  Activo No Corriente
219              47510001 - HP ACREED RETEN TRABAJADOR  Activo No Corriente

                                 Grupo  \
4           I. Inmovilizado intangible
5           I. Inmovilizado intangible
6           I. Inmovilizado intangible
7           I. Inmovilizado intangible
10           II. Inmovilizado material
..                                 ...
121  VI. Activos por impuesto diferido
141  VI. Activos por impuesto diferido
214  VI. Activos por impuesto diferido
216  VI. Activos por impuesto diferido
219  VI. Activos por impuesto diferido

                                              SubGrupo
4                         5. Aplicaciones informáticas
5                         5. Aplicaciones informáticas
6                         5. Aplicaciones informáticas
7                         5. Aplicaciones informáticas
10   2. Instalaciones técnicas y otro inmovilizado ...
..                                                 ...
121                       5. Otros activos financieros
141                       5. Otros activos financieros
214                       5. Otros activos financieros
216                       5. Otros activos financieros
219                       5. Otros activos financieros

[97 rows x 6 columns]

In [18]:
Balance['Subcuenta'].where(pd.to_numeric(Balance['Subcuenta'].str.extract(r'^(\d+)')[0]) < 1000).ffill()

4              206 Aplicaciones informáticas
5              206 Aplicaciones informáticas
6              206 Aplicaciones informáticas
7              206 Aplicaciones informáticas
10                            216 Mobiliario
                       ...
121        474 Activos por impuesto diferido
141                               572 Bancos
214                               572 Bancos
216                               572 Bancos
219    476 Organismos de la Seguridad Social
Name: Subcuenta, Length: 97, dtype: str

In [19]:
Balance['Cuenta'] = Balance['Subcuenta'].where(pd.to_numeric(Balance['Subcuenta'].str.extract(r'^(\d+)')[0]) < 10000).ffill()

In [20]:
Balance

,Subcuenta,Valor,Partida,Subpartida,Grupo,SubGrupo,Cuenta
4,206 Aplicaciones informáticas,"923003,2",ACTIVO,Activo No Corriente,I. Inmovilizado intangible,5. Aplicaciones informáticas,206 Aplicaciones informáticas
5,20600001 - CASH LESS DESARROLLO SOFTWARE,"923003,2",ACTIVO,Activo No Corriente,I. Inmovilizado intangible,5. Aplicaciones informáticas,206 Aplicaciones informáticas
6,2806 Amortización acumulada de aplicaciones in...,"-851691,6196",ACTIVO,Activo No Corriente,I. Inmovilizado intangible,5. Aplicaciones informáticas,2806 Amortización acumulada de aplicaciones in...
7,28060001 - AMORTACUMCASH LESS,"-851691,6196",ACTIVO,Activo No Corriente,I. Inmovilizado intangible,5. Aplicaciones informáticas,2806 Amortización acumulada de aplicaciones in...
10,216 Mobiliario,"27302,08147",ACTIVO,Activo No Corriente,II. Inmovilizado material,2. Instalaciones técnicas y otro inmovilizado ...,216 Mobiliario
...,...,...,...,...,...,...,...
121,4709 Hacienda Pública,"8171,91",5. Activos por impuesto corriente,Activo No Corriente,VI. Activos por impuesto diferido,5. Otros activos financieros,4709 Hacienda Pública
141,572 Bancos,"680354,50",1. Tesorería,Activo No Corriente,VI. Activos por impuesto diferido,5. Otros activos financieros,572 Bancos
214,4750 Hacienda Pública,"33167,95",6. Otras deudas con las Administraciones Públicas,Activo No Corriente,VI. Activos por impuesto diferido,5. Otros activos financieros,4750 Hacienda Pública
216,4751 Hacienda Pública,"34462,54",47500000 - HACIENDA PÚBLICA ACREEDORA PO,Activo No Corriente,VI. Activos por impuesto diferido,5. Otros activos financieros,4751 Hacienda Pública
219,476 Organismos de la Seguridad Social,"12845,25",47510001 - HP ACREED RETEN TRABAJADOR,Activo No Corriente,VI. Activos por impuesto diferido,5. Otros activos financieros,476 Organismos de la Seguridad Social

In [21]:
Balance['Cuenta'] = Balance['Cuenta'].where(pd.to_numeric(Balance['Subcuenta'].str.extract(r'^(\d+)')[0]) < 10000).ffill()

Balance['Cuenta'].where(pd.to_numeric(Balance['Subcuenta'].str.extract(r'^(\d+)')[0]) < 10000)

4                          206 Aplicaciones informáticas
5                                                    NaN
6      2806 Amortización acumulada de aplicaciones in...
7                                                    NaN
10                                        216 Mobiliario
                             ...
121                                4709 Hacienda Pública
141                                           572 Bancos
214                                4750 Hacienda Pública
216                                4751 Hacienda Pública
219                476 Organismos de la Seguridad Social
Name: Cuenta, Length: 97, dtype: str

In [22]:
Balance = Balance[~(pd.to_numeric(Balance['Subcuenta'].str.extract(r'^(\d+)')[0]) < 10000)]

In [23]:
Balance

,Subcuenta,Valor,Partida,Subpartida,Grupo,SubGrupo,Cuenta
5,20600001 - CASH LESS DESARROLLO SOFTWARE,"923003,2",ACTIVO,Activo No Corriente,I. Inmovilizado intangible,5. Aplicaciones informáticas,206 Aplicaciones informáticas
7,28060001 - AMORTACUMCASH LESS,"-851691,6196",ACTIVO,Activo No Corriente,I. Inmovilizado intangible,5. Aplicaciones informáticas,2806 Amortización acumulada de aplicaciones in...
11,21600001 - 5 SILLAS ERGONOMICAS,"2119,14",ACTIVO,Activo No Corriente,II. Inmovilizado material,2. Instalaciones técnicas y otro inmovilizado ...,216 Mobiliario
12,21600002 - 5 MESAS OFICINA DEMI,"1363,3134",ACTIVO,Activo No Corriente,II. Inmovilizado material,2. Instalaciones técnicas y otro inmovilizado ...,216 Mobiliario
13,21600003 - 5 CAJONERAS NIX,"1226,7466",ACTIVO,Activo No Corriente,II. Inmovilizado material,2. Instalaciones técnicas y otro inmovilizado ...,216 Mobiliario
...,...,...,...,...,...,...,...
96,26000002 - FIANZA OFICINA BAILEN 71,"4473,74",ACTIVO,Activo No Corriente,V. Inversiones financieras a largo plazo,5. Otros activos financieros,26 Fianzas y depósitos constituidos a largo plazo
97,26000003 - FIANZA PARKING ESTACIONAMIENTO,"317,871",ACTIVO,Activo No Corriente,V. Inversiones financieras a largo plazo,5. Otros activos financieros,26 Fianzas y depósitos constituidos a largo plazo
98,26000004 - FIANZA AUTOMOVIL AUDI Q2,"819,212432",ACTIVO,Activo No Corriente,V. Inversiones financieras a largo plazo,5. Otros activos financieros,26 Fianzas y depósitos constituidos a largo plazo
100,Activos por impuesto diferido,"35926,46325",ACTIVO,Activo No Corriente,VI. Activos por impuesto diferido,5. Otros activos financieros,26 Fianzas y depósitos constituidos a largo plazo
102,47420000 - DCHOSDEDUCY BONI PTES APLI,"35926,46325",ACTIVO,Activo No Corriente,VI. Activos por impuesto diferido,5. Otros activos financieros,474 Activos por impuesto diferido

In [24]:
# Configuración Año y Periodo (Establecidos en el inicio del script)

Año = BalanceFile[7:11]

Balance['Año'] = Año
Balance['Periodo'] = Periodo

* Ordenar Columnas:

In [25]:
Balance = Balance[['Año', 'Periodo', 'Partida', 'Subpartida', 'Grupo', 'SubGrupo', 'Cuenta', 'Subcuenta', 'Valor']]

In [26]:
Balance

,Año,Periodo,Partida,Subpartida,Grupo,SubGrupo,Cuenta,Subcuenta,Valor
5,2024,Anual,ACTIVO,Activo No Corriente,I. Inmovilizado intangible,5. Aplicaciones informáticas,206 Aplicaciones informáticas,20600001 - CASH LESS DESARROLLO SOFTWARE,"923003,2"
7,2024,Anual,ACTIVO,Activo No Corriente,I. Inmovilizado intangible,5. Aplicaciones informáticas,2806 Amortización acumulada de aplicaciones in...,28060001 - AMORTACUMCASH LESS,"-851691,6196"
11,2024,Anual,ACTIVO,Activo No Corriente,II. Inmovilizado material,2. Instalaciones técnicas y otro inmovilizado ...,216 Mobiliario,21600001 - 5 SILLAS ERGONOMICAS,"2119,14"
12,2024,Anual,ACTIVO,Activo No Corriente,II. Inmovilizado material,2. Instalaciones técnicas y otro inmovilizado ...,216 Mobiliario,21600002 - 5 MESAS OFICINA DEMI,"1363,3134"
13,2024,Anual,ACTIVO,Activo No Corriente,II. Inmovilizado material,2. Instalaciones técnicas y otro inmovilizado ...,216 Mobiliario,21600003 - 5 CAJONERAS NIX,"1226,7466"
...,...,...,...,...,...,...,...,...,...
96,2024,Anual,ACTIVO,Activo No Corriente,V. Inversiones financieras a largo plazo,5. Otros activos financieros,26 Fianzas y depósitos constituidos a largo plazo,26000002 - FIANZA OFICINA BAILEN 71,"4473,74"
97,2024,Anual,ACTIVO,Activo No Corriente,V. Inversiones financieras a largo plazo,5. Otros activos financieros,26 Fianzas y depósitos constituidos a largo plazo,26000003 - FIANZA PARKING ESTACIONAMIENTO,"317,871"
98,2024,Anual,ACTIVO,Activo No Corriente,V. Inversiones financieras a largo plazo,5. Otros activos financieros,26 Fianzas y depósitos constituidos a largo plazo,26000004 - FIANZA AUTOMOVIL AUDI Q2,"819,212432"
100,2024,Anual,ACTIVO,Activo No Corriente,VI. Activos por impuesto diferido,5. Otros activos financieros,26 Fianzas y depósitos constituidos a largo plazo,Activos por impuesto diferido,"35926,46325"
102,2024,Anual,ACTIVO,Activo No Corriente,VI. Activos por impuesto diferido,5. Otros activos financieros,474 Activos por impuesto diferido,47420000 - DCHOSDEDUCY BONI PTES APLI,"35926,46325"

* Pendiente Transformación: Desglosar Columnas correspondientes en {Id y Nombre}

In [27]:
# Division Columnas y creación columnas_id's: 

Balance[['Grupo_id', 'Grupo']] = Balance['Grupo'].str.split('. ', n = 1, expand = True)              # Grupo
Balance[['SubGrupo_id', 'SubGrupo']] = Balance['SubGrupo'].str.split('. ', n = 1, expand = True)     # SubGrupo
Balance[['Cuenta_id', 'Cuenta']] = Balance['Cuenta'].str.split(' ', n = 1, expand = True)            # Cuenta
Balance[['Subcuenta_id', 'Subcuenta']] = Balance['Subcuenta'].str.split(' - ', n = 1, expand = True) # Subcuenta

In [28]:
Balance.head(5)

,Año,Periodo,Partida,Subpartida,Grupo,SubGrupo,Cuenta,Subcuenta,Valor,Grupo_id,SubGrupo_id,Cuenta_id,Subcuenta_id
5,2024,Anual,ACTIVO,Activo No Corriente,Inmovilizado intangible,Aplicaciones informáticas,Aplicaciones informáticas,CASH LESS DESARROLLO SOFTWARE,"923003,2",I,5,206,20600001
7,2024,Anual,ACTIVO,Activo No Corriente,Inmovilizado intangible,Aplicaciones informáticas,Amortización acumulada de aplicaciones informá...,AMORTACUMCASH LESS,"-851691,6196",I,5,2806,28060001
11,2024,Anual,ACTIVO,Activo No Corriente,Inmovilizado material,Instalaciones técnicas y otro inmovilizado mat...,Mobiliario,5 SILLAS ERGONOMICAS,"2119,14",II,2,216,21600001
12,2024,Anual,ACTIVO,Activo No Corriente,Inmovilizado material,Instalaciones técnicas y otro inmovilizado mat...,Mobiliario,5 MESAS OFICINA DEMI,"1363,3134",II,2,216,21600002
13,2024,Anual,ACTIVO,Activo No Corriente,Inmovilizado material,Instalaciones técnicas y otro inmovilizado mat...,Mobiliario,5 CAJONERAS NIX,"1226,7466",II,2,216,21600003

In [29]:
Balance.columns

Index(['Año', 'Periodo', 'Partida', 'Subpartida', 'Grupo', 'SubGrupo',
       'Cuenta', 'Subcuenta', 'Valor', 'Grupo_id', 'SubGrupo_id', 'Cuenta_id',
       'Subcuenta_id'],
      dtype='str')

In [30]:
# Ordenamos el dataframe: 
Balance = Balance[['Año', 'Periodo', 'Partida', 'Subpartida', 'Grupo_id', 'Grupo', 'SubGrupo_id', 'SubGrupo',
                 'Cuenta_id', 'Cuenta', 'Subcuenta_id', 'Subcuenta', 'Valor']]

In [31]:
# Cambiamos tipo de dato de Valor de Object a Numeric:
Balance['Valor'] = Balance['Valor'].str.replace('.', '', regex=False)   # Elimina los puntos que separan miles
Balance['Valor'] = Balance['Valor'].str.replace(',', '.', regex=False)  # Reemplaza las comas por puntos decimales
Balance['Valor'] = pd.to_numeric(Balance['Valor'], errors='coerce')

In [32]:
Balance.head(10)

,Año,Periodo,Partida,Subpartida,Grupo_id,Grupo,SubGrupo_id,SubGrupo,Cuenta_id,Cuenta,Subcuenta_id,Subcuenta,Valor
5,2024,Anual,ACTIVO,Activo No Corriente,I,Inmovilizado intangible,5,Aplicaciones informáticas,206,Aplicaciones informáticas,20600001,CASH LESS DESARROLLO SOFTWARE,923003.200000
7,2024,Anual,ACTIVO,Activo No Corriente,I,Inmovilizado intangible,5,Aplicaciones informáticas,2806,Amortización acumulada de aplicaciones informá...,28060001,AMORTACUMCASH LESS,-851691.619600
11,2024,Anual,ACTIVO,Activo No Corriente,II,Inmovilizado material,2,Instalaciones técnicas y otro inmovilizado mat...,216,Mobiliario,21600001,5 SILLAS ERGONOMICAS,2119.140000
12,2024,Anual,ACTIVO,Activo No Corriente,II,Inmovilizado material,2,Instalaciones técnicas y otro inmovilizado mat...,216,Mobiliario,21600002,5 MESAS OFICINA DEMI,1363.313400
13,2024,Anual,ACTIVO,Activo No Corriente,II,Inmovilizado material,2,Instalaciones técnicas y otro inmovilizado mat...,216,Mobiliario,21600003,5 CAJONERAS NIX,1226.746600
14,2024,Anual,ACTIVO,Activo No Corriente,II,Inmovilizado material,2,Instalaciones técnicas y otro inmovilizado mat...,216,Mobiliario,21600004,4 ARCHIVADORES CARIN,1874.261600
15,2024,Anual,ACTIVO,Activo No Corriente,II,Inmovilizado material,2,Instalaciones técnicas y otro inmovilizado mat...,216,Mobiliario,21600005,6 ARCHIVADORES BISLEY,1935.481200
16,2024,Anual,ACTIVO,Activo No Corriente,II,Inmovilizado material,2,Instalaciones técnicas y otro inmovilizado mat...,216,Mobiliario,21600006,2 ARMARIOS CAPSA,899.457200
17,2024,Anual,ACTIVO,Activo No Corriente,II,Inmovilizado material,2,Instalaciones técnicas y otro inmovilizado mat...,216,Mobiliario,21600007,4 PUF REDONDO O CUADRADO,1428.559366
18,2024,Anual,ACTIVO,Activo No Corriente,II,Inmovilizado material,2,Instalaciones técnicas y otro inmovilizado mat...,216,Mobiliario,21600008,MESA DE JUNTAS DE MEDIDAS 200X120 SOBRE LAMINA...,1272.190380

### Resultado y Descarga:

In [33]:
Balance.head(4)

,Año,Periodo,Partida,Subpartida,Grupo_id,Grupo,SubGrupo_id,SubGrupo,Cuenta_id,Cuenta,Subcuenta_id,Subcuenta,Valor
5,2024,Anual,ACTIVO,Activo No Corriente,I,Inmovilizado intangible,5,Aplicaciones informáticas,206,Aplicaciones informáticas,20600001,CASH LESS DESARROLLO SOFTWARE,923003.2000
7,2024,Anual,ACTIVO,Activo No Corriente,I,Inmovilizado intangible,5,Aplicaciones informáticas,2806,Amortización acumulada de aplicaciones informá...,28060001,AMORTACUMCASH LESS,-851691.6196
11,2024,Anual,ACTIVO,Activo No Corriente,II,Inmovilizado material,2,Instalaciones técnicas y otro inmovilizado mat...,216,Mobiliario,21600001,5 SILLAS ERGONOMICAS,2119.1400
12,2024,Anual,ACTIVO,Activo No Corriente,II,Inmovilizado material,2,Instalaciones técnicas y otro inmovilizado mat...,216,Mobiliario,21600002,5 MESAS OFICINA DEMI,1363.3134

In [34]:
### Descarga arhivo: 
NombreArchivo = f"File.Balance{Año}.csv"
Balance.to_csv(NombreArchivo, index=False)

In [35]:
f"Archivo creado llamado: 'File.Balance{Año}.csv'"

"Archivo creado llamado: 'File.Balance2024.csv'"